### ISSUE TITLE
Peer Review-Technical

### ISSUE THREAD

**Issue by ebilal1** [BuntelanNasi/WebTechProject#4]
1. On the recipes page when I pressed on some of the pictures, it took me to a blank page. I just pressed on your code for "bolognese.html" but it didn't show me anything. I think maybe you need to push it?
2. I believe your sitemap page is also missing but I see it under your code. I think it is the same issue as the recipes page. I also think you should center the "About" description a little more.

**Comment by BuntelanNasi** [comment]
Hello ebilal1!

Thank you for the feedback! The code has been pushed, but there was no code in the first place; at that time, I only did some of the recipes, therefore, the blank pages on some of the food recipes. I made sure I put the sitemap on the bottom of all my pages, and I centered the about description more.
