### ISSUE TITLE
Peer Review-Content

### ISSUE THREAD

**Issue by ebilal1** [BuntelanNasi/WebTechProject#5]
1. I was a little confused on the home page because I am not sure what "Makan Bareng" means so a short description would be great! I know that you provided a description in the "About" section but a very short sentence underneath would make it easier for viewers.
2. On the "Contact" page it was a little difficult for me to see "Customer Feedback" so I think a darker color would be easier for the viewers. 

Dylan, I loved navigating through your website, and I especially loved the color scheme and the different types of aesthetics you used. These recipes look really delicious and I can't wait to try them!

**Comment by BuntelanNasi** [comment]
Hi again ebilal1,

I added a short description on the index page on what makan bareng meant and I made the customer feedback font darker so that people are able to see it more clearly.

Thank you for the nice words on the website and I hope your website goes well!
